dist: latest
language: python
matrix:
  include:
    - python: 2.7
      env: TOXENV=django111
    - python: 3.6
      env: TOXENV=django111
    - python: 3.7
      env: TOXENV=django111
    - python: 3.6
      env: TOXENV=django20
    - python: 3.6
      env: TOXENV=django21
    - python: 3.7
      env: TOXENV=django20
    - python: 3.7
      env: TOXENV=django21
    - python: 3.5
      env: TOXENV=quality
    - python: 3.6
      env: TOXENV=docs
cache:
- pip
before_install:
- pip install --upgrade pip
- pip install --upgrade setuptools
install:
- make upgrade
- pip install -r requirements/travis.txt
script:
- tox
after_success:
- codecov
deploy:
  provider: pypi
  user: edx
  distributions: sdist bdist_wheel
  on:
    tags: true
    condition: "$TOXENV = quality"
  password:
    secure: hf9pUeHGCfFpopmkOg+kdHQf/pfv5zIs1Sg8r1WaSqpIGwVo+blhE40cOmWo9NXPRus6HwhtDPSHkxzaZ78Vn9wWn8yix9FqQFXSoY5uGwoIO7GhCdOgW8HrgGpcH5mT82BKghKSAd1N5eWg/b4xNa/AswV8LhnYeVqyosLGHy8aBLSCDFtoTH//vA11TDaZL/uklvPYfeGDEudZ6iBPl4YO3na2n5CfEDjvTNVoadoqDUEJa1OQ2FUZrc97h3X9nWPXxeZTqyQH/c0s22zYlUeKBt23ztYQPSMhiF1GiPc3xTx0D4fC5/0oI8qMMCh6Mmu3U88pnbChcJKO9KoIJ8soIBrk/hPKCqgNanDKJu1NxWROP9/+22RFalKRXltppSdo+Ua0vs64DlLJkaWsAh9y1FfvAiniQ+k6DBiLIi1Y6fACawnTVEetq4rvP571Vt+sWDA/i6DAwGjViLllWM/Djzq5pOfYXp4lkXAk36S3NsmsWvMiaVP0tnrmL2Bx5lWmd+tXya7s6X1gjkRnId447iu9PMMeM00Ny1A6wNvQ4NXiTYMlwENsqdx9aeyBM/MhfciszcnnrVUAd63wf8Gx+mMZDRT2PiRGj1cqTpN8hlI0yuomaOqFhICkhg3OM2v7/ZT+iUdNXVEDEs+uhBf8IfGYH44WBLKtNtJ9BWQ=
